manager:
  #电影管理模式，link为文件创建硬链接模式 copy为复制模式
  mode: 'link'
  #值为true或false，是否将目标电影文件夹，按国家名做一次分类；文件结构示范：/video/华语/爱情神话 (2022)/爱情神话 (2022).mkv
  use_country_folder: false
  #下载器的路径映射及类型，如果配置了这个；sync_movies智能下载任务做硬链接时，会采用这个映射关系；监测手动提交到下载器下载的种子完成状态也会依赖也会依赖这个信息；
  download_paths:
    #下载工具的种子保存路径，可以去下载器点一个种子，看下具体的保存路径
    - download_path: '/downloads/电影'
      #容器内映射的路径，要确保容器可以访问到这个路径，可以进容器命令行 ls /video/电影 看看能不能找到，找不到肯定是docker的存储目录没有挂载
      container_path: '/video/电影'
      link_path: '/video/link/电影'
      #影视类型 movie表示电影 tv表示剧集 严格区分大小写；严格确保你目录中只有这一种类型的影视，如果错了，会导致识别混乱；
      movie_type: 'movie'
      #这里只是一个示范，一定要按你下载器的真实设置，以及给docker容器挂载的路径去配置,download_path不可重复，重复了也会出问题
    - download_path: '/downloads/剧集'
      container_path: '/video/剧集'
      link_path: '/video/link/剧集'
      movie_type: 'tv'
tmdb:
  #获取TMDB apikey的页面，https://www.themoviedb.org/settings/api 页面中的API 密钥
  api_key: '复制到这里'